version: '3.9'

networks:
  appnet:

services:
  volvowebapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=Server=db;Database=VolvoDb;User Id=sa;Password=pa55w0rd!;
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./dpkeys:/var/dpkeys
    networks:
      - appnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "pa55w0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet