version: '3.4'

networks:
  appnet:
    driver: bridge

services:
  volvodb:
    container_name: volvo-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
    ports:
      - "1433:1433"
    networks:
      - appnet

  volvowebapp:
    container_name: volvo-web-app
    image: ${DOCKER_REGISTRY-}volvowebapp
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - volvodb
    environment:
      - ConnectionStrings__Default=Server=volvodb;Database=VolvoDb;User Id=sa;Password=pa55w0rd!;
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./dpkeys:/var/dpkeys
    networks:
      - appnet